# Generated by Django 4.2.2 on 2023-10-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymodel',
            name='status',
            field=models.CharField(choices=[('0', 'Aktif'), ('1', 'Non Aktif'), ('2', 'Selesai')], default=0, max_length=1, verbose_name='Status Survei'),
        ),
    ]
