# Generated by Django 4.2.2 on 2023-10-29 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='User Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='User Name')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('theme', models.CharField(choices=[('0', 'dark'), ('1', 'light')], default='1', max_length=1, verbose_name='User Theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
