# Generated by Django 4.2.2 on 2023-10-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('0', 'true'), ('1', 'false')], default='1', max_length=1, verbose_name='User Theme Dark Mode'),
        ),
    ]
