# Generated by Django 4.2.2 on 2023-10-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme_condense',
            field=models.CharField(choices=[('0', 'true'), ('1', 'false')], default='1', max_length=1, verbose_name='User Theme Left Side Condense'),
        ),
    ]
