# Generated by Django 4.2.2 on 2023-10-29 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_survey', '0001_initial'),
        ('master_petugas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alokasipetugas',
            name='petugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='master_alokasi_petugas', to='master_petugas.masterpetugas', verbose_name='Kode Petugas'),
        ),
        migrations.AlterField(
            model_name='alokasipetugas',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='master_alokasi_role', to='master_petugas.rolemitra', verbose_name='Jabatan Petugas'),
        ),
        migrations.AlterField(
            model_name='alokasipetugas',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='master_alokasi_survey', to='master_survey.surveymodel', verbose_name='Survei/Sensus'),
        ),
        migrations.DeleteModel(
            name='RekeningPetugas',
        ),
    ]
