# Generated by Django 4.2.2 on 2023-10-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_petugas', '0002_alter_alokasipetugas_petugas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpetugas',
            name='status',
            field=models.CharField(choices=[('0', 'Aktif'), ('1', 'Non Aktif'), ('3', 'Organik'), ('4', 'Blacklist')], max_length=1, verbose_name='Status Mitra'),
        ),
    ]
