# Generated by Django 4.2.2 on 2023-10-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_petugas', '0003_alter_masterpetugas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpetugas',
            name='status',
            field=models.CharField(choices=[('0', 'Aktif'), ('1', 'Non Aktif'), ('2', 'Organik'), ('3', 'Blacklist')], max_length=1, verbose_name='Status Mitra'),
        ),
    ]
