# Generated by Django 4.2.2 on 2023-10-12 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndikatorKegiatanPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IndikatorPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_indikator', models.CharField(max_length=128, verbose_name='Indikator Penilaian')),
                ('deskripsi_penilaian', models.TextField(blank=True, null=True, verbose_name='Deskripsi Penilaian')),
            ],
        ),
        migrations.CreateModel(
            name='KegiatanPenilaianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=256, verbose_name='Nama Kegiatan Penilaian')),
                ('tgl_penilaian', models.DateField(verbose_name='Tanggal Penilaian')),
                ('status', models.CharField(choices=[('0', 'Aktif'), ('1', 'Tidak Aktif')], default=0, max_length=1, verbose_name='Status Penilaian')),
            ],
        ),
        migrations.CreateModel(
            name='MasterNilaiPetugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.SmallIntegerField(blank=True, null=True, verbose_name='Nilai Kegiatan Petugas')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan Personal')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='indikator_kegiatan_penilaian', to='master_penilaian.indikatorkegiatanpenilaian')),
            ],
        ),
    ]
