# Generated by Django 4.2.2 on 2023-10-12 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_survey', '0001_initial'),
        ('master_penilaian', '0001_initial'),
        ('master_petugas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternilaipetugas',
            name='petugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='nilai_petugas', to='master_petugas.alokasipetugas'),
        ),
        migrations.AddField(
            model_name='kegiatanpenilaianmodel',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='penilaian_survei', to='master_survey.surveymodel'),
        ),
        migrations.AddField(
            model_name='indikatorkegiatanpenilaian',
            name='indikator_penilaian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='indikator_penilaian_petugas', to='master_penilaian.indikatorpenilaian'),
        ),
        migrations.AddField(
            model_name='indikatorkegiatanpenilaian',
            name='kegiatan_penilaian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='kegiatan_penilaian_petugas', to='master_penilaian.kegiatanpenilaianmodel'),
        ),
    ]
