# Generated by Django 4.2.2 on 2023-10-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_petugas', '0004_alter_masterpetugas_status'),
        ('master_penilaian', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatanpenilaianmodel',
            name='role_permitted',
            field=models.ManyToManyField(to='master_petugas.rolemitra'),
        ),
    ]
